version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 350
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 150
  similar-code:
    config:
      threshold: 60
exclude_patterns:
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/__tests__/"
  - "**/vendor/"
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/*.stories.js"
  - "**/GameContextMock.js"
