runtime: nodejs14
entrypoint: npm run prod-server
instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0

env_variables:
  NODE_ENV: $NODE_ENV
  SENTRY_DSN: $SENTRY_DSN
  ENVIRONMENT: $ENVIRONMENT
