[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = '''
    max-age=2592000,
    public,
    immutable'''
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    public,
    immutable'''
