name: Merge me!

on:
  # Triggers when a workflow is run.
  workflow_run:
    workflows: ["Test octoboard"]
    branches-ignore: ["master"]
    types:
      - completed

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dependabot[bot]
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
          PRESET: DEPENDABOT_MINOR
          DISABLED_FOR_MANUAL_CHANGES: "true"
