name: octoboard

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run prettier-ci

  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run storybook-ci
