name: Corona-games

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.8.0"
      - run: npm install
      - run: npm run prettier-ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.8.0"
      - run: npm install
      - run: npm run build --if-present
