name: Deploy PR to octoboard-development

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run prettier-ci
      - run: npm run lint
  storybook:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run storybook-ci
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
        with:
          coverageCommand: npm run test-ci
  deploy_server:
    name: Deploy server
    runs-on: ubuntu-latest
    needs: [test, storybook]
    if: contains(github.event.pull_request.labels.*.id, 2818529465)
    environment:
      name: octoboard-development-server
      url: https://${{ github.head_ref }}-dot-octoboard-development.appspot.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          SENTRY_DSN: ${{ secrets.APP_SENTRY_DSN }}
          ENVIRONMENT: staging
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: octoboard-development
          service_account_key: ${{ secrets.APP_ENGINE_SERVICE_ACCOUNT_OCTOBOARD_DEVELOPMENT }}
      - name: Deploy to App Engine
        run: gcloud app deploy --quiet --no-promote --version=${{ github.head_ref }}
  deploy_client:
    name: Deploy client
    runs-on: ubuntu-latest
    needs: deploy_server
    if: contains(github.event.pull_request.labels.*.id, 2818529465)
    environment:
      name: octoboard-development-client
      url: ${{ steps.preview.outputs.details_url }}
    env:
      REACT_APP_API_ROOT: https://${{ github.head_ref }}-dot-octoboard-development.appspot.com
      REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
      REACT_APP_ENVIRONMENT: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm ci && npm run build
      - name: Preview
        id: preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OCTOBOARD_DEVELOPMENT }}"
          projectId: octoboard-development
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
